services:
  proxy_udp:
    build:
      context: .
      dockerfile: Dockerfile
      target: stone
      args:
        - build_time_proxy=${build_time_proxy}
    restart: "${restart:-no}"
    command: 
      - "127.0.0.53:53/udp"
      - "172.17.0.1:53/udp"
    network_mode: "host"
    # The following settings for "ports" are not required because the network adapter on the docker host is used transparently in "host" network_mode.
    #ports:
    #  - target: 53
    #    published: 53
    #    protocol: udp
    #    mode: host
  proxy_tcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: stone
      args:
        - build_time_proxy=${build_time_proxy}
    restart: "${restart:-no}"
    command: 
      - "127.0.0.53:53"
      - "172.17.0.1:53"
    network_mode: "host"
    # The following settings for "ports" are not required because the network adapter on the docker host is used transparently in "host" network_mode.
    #ports:
    #  - target: 53
    #    published: 53
    #    protocol: tcp
    #    mode: host
